### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by ningsongshen**
There is only one npm dependency...@mobitar is there something like ncu that you guys use for gems?

### CODE REVIEW

**Comment by mobitar** [comment]
It would just be `bundle update` or something like that.

**Comment by ningsongshen** [comment]
After updating the gems, I was able to complete the process flow and obtain an integration code.

**Comment by mobitar** [comment]
@ningsongshen can you see why the deploy failed? https://github.com/standardnotes/filesafe-relay/runs/858429873?check_suite_focus=true

**Comment by ningsongshen** [comment]
I think it means that the `yarn.lock` file was not updated. Which is true...because I used ncu/npm to update the packages.

I'm a bit confused, should I be using yarn or npm for this repository?

**Comment by mobitar** [comment]
Yarn I believe

**Pull request merged**
